export const Constants = {
    TITLE_MAX_LENGTH: 50,
    DESCRIPTION_MAX_LENGTH: 500,
    USERNAME_MAX_LENGTH: 50,

    ENCODING_MAX_LENGTH: 10,
    MIME_MAX_LENGTH: 20,
    FILENAME_MAX_LENGTH: 100

}
